<a href="https://colab.research.google.com/github/AmnaShaheena/Bioinformatics-CSH4123-Practical/blob/main/Day04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

can contains different datatypes in a one list
can repeat same values

In [4]:
List=['Apple',20,'Orange',15,'Apple']

In [3]:
print(List)

['Apple', 20, 'Orange', 15]


In [5]:
print(len(List))

5


In [6]:
print(type(List))

<class 'list'>


In [7]:
number=[1,2,3,4,5,6]
print(number)

[1, 2, 3, 4, 5, 6]


In [8]:
number[2]

3

In [9]:
len(number)

6

In [11]:
number.append(7)

In [12]:
print(number)

[1, 2, 3, 4, 5, 6, 7]


In [13]:
print(type(number))

<class 'list'>


In [14]:
number.pop(3)

4

In [15]:
print(number)

[1, 2, 3, 5, 6, 7]


In [18]:
number.clear()

In [19]:
print(number)

[]


In [20]:
number=[1,2,3,4,5,6]
number.copy()

[1, 2, 3, 4, 5, 6]

In [23]:
number.count(5)

1

In [27]:
List.extend([8,51,67])
print(List)

['Apple', 20, 'Orange', 15, 'Apple', 8, 51, 67, 8, 51, 67]


In [28]:
List.index('Apple')

0

In [29]:
List.insert(2,'Mango')
print(List)

['Apple', 20, 'Mango', 'Orange', 15, 'Apple', 8, 51, 67, 8, 51, 67]


In [31]:
List.remove('Apple')
print(List)

[20, 'Mango', 'Orange', 15, 8, 51, 67, 8, 51, 67]


In [38]:
numbers=[22,4,93,14]
numbers.sort()
print(numbers)

[4, 14, 22, 93]


In [39]:
import numpy as np

In [43]:
list=[1,2,3,4,5,6,7,8,9]
list
np_array=np.array(list)
np_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
import numpy as np
rows=3
cols=3
list_of_list=[[j for j in range(cols)]for i in range(rows)]
list_of_list



[[0, 1, 2], [0, 1, 2], [0, 1, 2]]

In [54]:
import numpy as np
x=3
y=3
z=3

list_of_list=[[[j for j in range(y)]for i in range(x)]for k in range(z)]
list_of_list


[[[0, 1, 2], [0, 1, 2], [0, 1, 2]],
 [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
 [[0, 1, 2], [0, 1, 2], [0, 1, 2]]]

In [57]:
list_of_list[0][1][1]

1

In [59]:
import numpy as np
arr_1=[2,6,8,3]
arr_2=[3,98,1,3]
arr_3=[5,1,0,5]

array_3d=np.array([arr_1,arr_2,arr_3])
array_3d


array([[ 2,  6,  8,  3],
       [ 3, 98,  1,  3],
       [ 5,  1,  0,  5]])

**Q1:create an evenly spaced array of numbers based on given start and stop values**

In [61]:

import numpy as np
evenly_spaced_array = np.linspace(0, 10, 5)

print("Evenly spaced array:")
print(evenly_spaced_array)

Evenly spaced array:
[ 0.   2.5  5.   7.5 10. ]


**Q2:create an array of zeros that be filled with data later**

In [63]:

import numpy as np

zeros_array = np.zeros((2, 3))

print("Array of zeros:")
print(zeros_array)

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]]


**Q3:create an arrays of ones**

In [65]:

import numpy as np
ones_array=np.ones((2,3))
print("Array of oness:")
print(ones_array)

Array of oness:
[[1. 1. 1.]
 [1. 1. 1.]]


**Q4:create array of random floats between zero and one**

In [66]:

import numpy as np
random_floats_array = np.random.rand(3, 2)

print("Array of random floats between 0 and 1:")
print(random_floats_array)

Array of random floats between 0 and 1:
[[0.80296416 0.11978218]
 [0.17765612 0.84532196]
 [0.99696552 0.14658223]]


**Q5:create 1D array and insert the values 1,2,3,4,5 and access the following elemnts**
*   1st element
*    2nd element
*   range of elements from 1st to 3rd
*   range of elements from 2nd element
*   range of elements from index==2
  


In [67]:
import numpy as np
one_d_array = np.array([1, 2, 3, 4, 5])
print("Original 1D array:", one_d_array)

Original 1D array: [1 2 3 4 5]


In [68]:
# Access the 1st element (index 0)
first_element = one_d_array[0]
print("\n1st element:", first_element)


1st element: 1


In [69]:
# Access the 2nd element (index 1)
second_element = one_d_array[1]
print("2nd element:", second_element)

2nd element: 2


In [70]:
# Access a range of elements from the 1st to the 3rd (indices 0, 1, 2)
# Slicing is inclusive of the start index and exclusive of the stop index
range_1_to_3 = one_d_array[0:3]
print("Range of elements from 1st to 3rd:", range_1_to_3)

Range of elements from 1st to 3rd: [1 2 3]


In [71]:
# Access a range of elements from the 2nd element to the end
# Leaving the stop index empty goes to the end of the array
range_from_2nd = one_d_array[1:]
print("Range of elements from 2nd element:", range_from_2nd)

Range of elements from 2nd element: [2 3 4 5]


In [72]:
# Access a range of elements from index 2 to the end
range_from_index_2 = one_d_array[2:]
print("Range of elements from index 2:", range_from_index_2)

Range of elements from index 2: [3 4 5]
